staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-worldchain-1
      url: https://worldchain-sepolia.g.alchemy.com/public

production-settings:
  rpcs:
    - chain-name: ethereum-mainnet
      url: ${ETH_MAINNET_RPC_URL}
    - chain-name: ethereum-mainnet-worldchain-1
      url: ${WORLD_CHAIN_RPC_URL}
